---
title: "Bitácora"
author: "La Doñita, El Tali"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Productos a generar (uso interno)

- Esquema.

- Bloque teórico y de definición de proyecto:

  - Día 0
    - Presentación de los estudiantes (quiénes son, qué esperan del curso, etc.)
    - Presentación del curso, objetivos, metodología, evaluación, etc.
    - Presentación de la materia y su importancia en el contexto actual.
    - Introducción a la modalidad de enseñanza (aprendizaje basado en ...), descripción básica de las herramientas tecnológicas que se utilizarán durante el curso, proyectos, prácticas, exámenes.

  - Días 1 a 3. Definición de proyecto.
  - Unidad 1 a 4 (teoría). (¡PRÓXIMO ENCUENTRO!). Esto se divide en parte teórica y parte de temas de proyectos con ejemplos aplicados para que puedan ver de qué trata cada tema.
  - Prácticas de semanas 1 a 4, guías de prácticas
  - ¿Unidades 5 en adelante?
  - Prácticas de semana 5 en adelante
  - Guía de proyecto (con los temas, metodología, cronograma, recursos tecnológicos y analógicos disponibles, etc.)
  
- Lista de posibles proyectos/ideas de investigación, proyectos aplicados (no olvidarlos), lista dinámica/expandible por estudiantes

- Lista de técnicas imprescindibles de la materia en cuestión

- Programas de asignaturas reformados

- Ver asignaturas Conservación y Geomorfología

# 11 de agosto, 2025

## ¿Qué nos propusimos hoy?

- ~~Lista de posibles proyectos/ideas de investigación, proyectos aplicados (no olvidarlos), lista dinámica/expandible por estudiantes. SÍ~~

~~- Definición de día 0~~

- Definición del primer mes de clases. NO.

## ¿Qué logramos hoy?

- Iniciar la guía de proyecto y organizamos los temas.

- Definición de día 0

# 13 de agosto, 2025

## ¿Qué nos propusimos hoy?

- Actualizar programas de asignaturas.

  - Editada parte básica/común de los programas de ambas asignaturas.
  - Reestructurado el programa a cuatro unidades.

- Diapositivas de bienvenida.

- Unidad 1 a 4 (teoría). (¡PRÓXIMO ENCUENTRO!). Esto se divide en parte teórica y parte de temas de proyectos con ejemplos aplicados para que puedan ver de qué trata cada tema.

  - Crear la clase de la Unidad 1 de Ecología II (Fundamentos de Ecología de Poblaciones) usando uno o varios de los recursos de aprendizajes.

- Prácticas de semanas 1 a 4, guías de prácticas.

- ...

## ¿Qué logramos hoy?

~~- Actualizar programas de asignaturas. SÍ~~

  ~~- Editada parte básica/común de los programas de ambas asignaturas. SÍ~~
  ~~- Reestructurado el programa a cuatro unidades. SÍ~~

~~- Diapositivas de bienvenida. PARCIAL~~

NOS QUEDAMOS AQUÍ:

- Unidad 1 a 4 (teoría). (¡PRÓXIMO ENCUENTRO!). Esto se divide en parte teórica y parte de temas de proyectos con ejemplos aplicados para que puedan ver de qué trata cada tema. NO

  - Crear la clase de la Unidad 1 de Ecología II (Fundamentos de Ecología de Poblaciones) usando uno o varios de los recursos de aprendizajes. NO

- Prácticas de semanas 1 a 4, guías de prácticas. NO


